// Generated by Haxe 4.3.4
(function ($hx_exports, $global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var App = $hx_exports["App"] = function() {
	this.bookmark = -1;
	this.location = [];
	var _gthis = this;
	this.buffer = new Buffer();
	harrow_Library.ESCAPE = ":";
	harrow_Random.dice = Dice.roll;
	var storydata = window.document.querySelector("tw-storydata");
	this.story = Parser.get(storydata);
	this.novel = new harrow_Runtime(this.story);
	this.novel.onText = $bind(this,this.onText);
	this.novel.onDialogue = $bind(this,this.onDialogue);
	this.novel.onTransition = $bind(this,this.onTransition);
	this.novel.onEvent = $bind(this,this.onEvent);
	this.novel.onClose = $bind(this,this.onEnd);
	this.novel.onEnd = $bind(this,this.onEnd);
	this.cover = window.document.querySelector("cover");
	this.start = window.document.querySelector("start");
	this.transition = window.document.querySelector("transition");
	this.imagebox = window.document.querySelector("imagebox");
	this.dialogue = window.document.querySelector("dialogue");
	this.textbox = window.document.querySelector("textbox");
	this.button = window.document.querySelector("continue");
	this.button.textContent = "Continue";
	this.button.setAttribute("role","button");
	this.button.style.display = "none";
	this.button.onclick = function(event) {
		_gthis.onClick();
	};
	window.document.querySelector("chapter").innerHTML = storydata.getAttribute("name");
	var style = window.document.createElement("style");
	style.innerHTML = window.document.querySelector("#twine-user-stylesheet").innerHTML;
	window.document.querySelector("body").appendChild(style);
	var script = window.document.createElement("script");
	script.innerHTML = window.document.querySelector("#twine-user-script").innerHTML;
	window.document.querySelector("body").appendChild(script);
	var passage = window.document.querySelector("tw-passagedata[name=\"StoryAuthor\"]");
	var tmp = passage != null ? passage.innerHTML : "Story by Author";
	window.document.querySelector("author").innerHTML = tmp;
	window.document.querySelector("name").innerHTML = storydata.getAttribute("name");
	this.settings = new Settings(this.story,storydata);
	window.document.querySelector("close").onclick = function(event) {
		_gthis.settings.close();
	};
	window.document.querySelector("open").onclick = function(event) {
		_gthis.settings.open();
	};
	window.document.querySelector("page").id = "title";
	this.start.onclick = function(event) {
		window.document.querySelector("page").removeAttribute("id");
		_gthis.novel.nextPage();
	};
};
App.__name__ = true;
App.main = function() {
	App.ME = new App();
};
App.prototype = {
	onClick: function() {
		this.button.style.display = "none";
		this.textbox.innerHTML = "";
		this.novel.nextPage();
	}
	,showText: function() {
		this.button.style.display = "block";
		if(Config.fadeText) {
			this.fade(this.textbox);
		}
	}
	,onText: function(text,name) {
		var limit = this.imagebox.style.display == "block" ? Config.maxHeight - 20 : Config.maxHeight;
		var paragraph = "<p>" + this.getText(text) + "</p>";
		this.textbox.innerHTML += this.buffer.get();
		if(this.currentFillRatio() > limit) {
			this.buffer.set(paragraph);
			this.showText();
			return;
		}
		this.textbox.innerHTML += paragraph;
		var full = this.currentFillRatio() > limit;
		var next = this.novel.story.look(this.novel.story.page + 1);
		var last = next == null;
		if(last) {
			this.showText();
		}
		if(last) {
			return;
		}
		if(full && next.type == "dialogue") {
			this.novel.nextPage();
		}
		if(full && next.type != "dialogue") {
			this.showText();
		}
		if(full) {
			return;
		}
		var allowed = next.type == "text" || next.type == "dialogue" || next.type == "event";
		if(next.type == "event") {
			if(next.data == "return") {
				allowed = false;
			}
			if(next.data == "scene") {
				allowed = false;
			}
		}
		if(allowed) {
			this.novel.nextPage();
		}
		if(!allowed) {
			this.showText();
		}
	}
	,getText: function(entry) {
		if(!Config.speaker) {
			return entry;
		}
		var raw = StringTools.replace(entry,"\\:",harrow_Library.DIVIDE);
		var key = raw.indexOf(":");
		if(key == -1) {
			return entry;
		}
		var name = StringTools.trim(HxOverrides.substr(raw,0,key));
		var text = StringTools.trim(HxOverrides.substr(raw,key + 1,null));
		name = StringTools.replace(name,harrow_Library.DIVIDE,":");
		text = StringTools.replace(text,harrow_Library.DIVIDE,":");
		return "<span class=\"speaker\">" + name + "</span>" + text;
	}
	,currentFillRatio: function() {
		if(this.textbox.clientHeight <= 0) {
			return 0;
		}
		var last = this.textbox.lastElementChild;
		if(last == null) {
			return 0;
		}
		var pageRect = this.textbox.getBoundingClientRect();
		var lastRect = last.getBoundingClientRect();
		var contentHeight = lastRect.bottom - pageRect.top;
		return Math.min(100,contentHeight / this.textbox.clientHeight * 100);
	}
	,onDialogue: function(choices) {
		var _gthis = this;
		if(this.buffer.full()) {
			this.textbox.innerHTML += this.buffer.get();
		}
		if(Config.fadeText) {
			this.fade(this.textbox);
		}
		this.dialogue.removeAttribute("id");
		if(choices.length > Config.maxVertical) {
			this.dialogue.id = "horizontal";
		}
		var _g = 0;
		while(_g < choices.length) {
			var entry = [choices[_g]];
			++_g;
			var choice = window.document.createElement("choice");
			choice.setAttribute("role","button");
			choice.innerHTML = harrow_Format.variable(entry[0].text);
			var allowed = entry[0].mode == "empty" ? true : harrow_Logic.condition(entry[0].mode);
			if(!allowed) {
				choice.className = "disabled";
			}
			choice.onclick = (function(entry) {
				return function(event) {
					_gthis.onSelect(entry[0].type,entry[0].data);
				};
			})(entry);
			this.dialogue.appendChild(choice);
		}
	}
	,onSelect: function(type,data) {
		this.dialogue.innerHTML = "";
		this.textbox.innerHTML = "";
		if(type == "route" && data != "return") {
			this.story.move(data);
		}
		if(data == "return" && this.bookmark != -1) {
			this.story.turn(this.bookmark);
		}
		if(type == "variable") {
			harrow_Logic.variable(data);
		}
		this.novel.nextPage();
	}
	,onEvent: function(type,data) {
		switch(type) {
		case "bar":
			this.buffer.set(Render.bar(data));
			break;
		case "bookmark":
			this.bookmark = data == "clear" ? -1 : this.story.page - 1;
			break;
		case "chapter":
			window.document.querySelector("chapter").innerHTML = harrow_Format.string(data);
			break;
		case "config.assets.folder":
			Config.folder = data;
			break;
		case "config.dialogue.vertical":
			Config.maxVertical = Std.parseInt(data);
			break;
		case "config.fade.image":
			Config.fadeImage = data == "true";
			break;
		case "config.fade.text":
			Config.fadeText = data == "true";
			break;
		case "config.parse.speaker":
			Config.speaker = data == "true";
			break;
		case "config.settings.title":
			Config.settings = harrow_Format.string(data);
			break;
		case "config.text.end":
			Config.endText = harrow_Format.string(data);
			break;
		case "config.text.fill":
			Config.maxHeight = Std.parseInt(data);
			break;
		case "dice":
			this.buffer.set(Render.dice(data));
			break;
		case "image":
			this.imageEvent(data);
			break;
		case "return":
			if(this.bookmark != -1) {
				this.story.turn(this.bookmark);
			}
			break;
		case "scene":
			this.sceneEvent(data);
			break;
		case "stat":
			this.buffer.set(Render.stat(data));
			break;
		default:
		}
	}
	,sceneEvent: function(data) {
		if(data == "close") {
			var page = this.location.pop();
			if(page != null) {
				this.story.turn(page);
			}
		} else if(data == "clear") {
			this.location = [];
		} else {
			this.location.push(this.story.page);
			this.story.move(data);
		}
	}
	,imageEvent: function(data) {
		if(data == "show") {
			window.document.querySelector("page").className = "novel";
			this.imagebox.style.display = "block";
		} else if(data == "hide") {
			window.document.querySelector("page").removeAttribute("class");
			this.imagebox.style.display = "none";
		} else {
			window.document.querySelector("page").className = "novel";
			this.imagebox.style.backgroundImage = "url('" + Config.folder + data + "')";
			this.imagebox.style.display = "block";
			if(Config.fadeImage) {
				this.fade(this.imagebox);
			}
		}
	}
	,fade: function(element,duration,from,to) {
		if(to == null) {
			to = 1;
		}
		if(from == null) {
			from = 0;
		}
		if(duration == null) {
			duration = 300;
		}
		element.style.transition = "none";
		element.style.opacity = from == null ? "null" : "" + from;
		element.getBoundingClientRect();
		element.style.transition = "opacity " + duration + "ms";
		element.style.opacity = to == null ? "null" : "" + to;
	}
	,onTransition: function(name) {
		var _gthis = this;
		var hide = function() {
			_gthis.transition.style.zIndex = "-1";
		};
		var fade = function() {
			_gthis.transition.className = "hidden";
			haxe_Timer.delay(hide,600);
			_gthis.novel.nextPage();
		};
		this.transition.style.zIndex = "600";
		this.transition.className = "active";
		haxe_Timer.delay(fade,900);
	}
	,onEnd: function() {
		this.buffer.clear();
		this.textbox.innerHTML = Config.endText;
		if(Config.fadeText) {
			this.fade(this.textbox);
		}
		this.button.textContent = "Restart";
		this.button.style.display = "block";
		this.button.onclick = function(event) {
			window.location.reload();
		};
	}
};
var Buffer = function() {
	this.content = "";
};
Buffer.__name__ = true;
Buffer.prototype = {
	full: function() {
		return this.content.length > 0;
	}
	,get: function() {
		var result = this.content;
		this.content = "";
		return result;
	}
	,set: function(text) {
		this.content += text;
	}
	,clear: function() {
		this.content = "";
	}
};
var Config = function() { };
Config.__name__ = true;
var Dice = function() { };
Dice.__name__ = true;
Dice.roll = function(entry) {
	var text = entry.toLowerCase();
	var keys = text.split("d");
	if(keys.length == 1) {
		return Dice.random(1,Std.parseInt(text));
	}
	var pool = Std.parseInt(keys.shift());
	var side = keys.shift();
	var type = side.charAt(side.length - 1);
	if(type == "h" || type == "l") {
		side = side.substring(0,side.length - 1);
	}
	var rolls = [];
	var total = 0;
	var _g = 0;
	var _g1 = pool;
	while(_g < _g1) {
		var i = _g++;
		var take = Dice.random(1,Std.parseInt(side));
		total += take;
		rolls.push(take);
	}
	rolls.sort(function(a,b) {
		return a - b;
	});
	if(type == "l") {
		return rolls.shift();
	}
	if(type == "h") {
		return rolls.pop();
	}
	return total;
};
Dice.random = function(min,max) {
	return min + Math.floor((max - min + 1) * Math.random());
};
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
EReg.__name__ = true;
EReg.prototype = {
	match: function(s) {
		if(this.r.global) {
			this.r.lastIndex = 0;
		}
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		if(this.r.m != null && n >= 0 && n < this.r.m.length) {
			return this.r.m[n];
		} else {
			throw haxe_Exception.thrown("EReg::matched");
		}
	}
	,matchedPos: function() {
		if(this.r.m == null) {
			throw haxe_Exception.thrown("No string matched");
		}
		return { pos : this.r.m.index, len : this.r.m[0].length};
	}
	,matchSub: function(s,pos,len) {
		if(len == null) {
			len = -1;
		}
		if(this.r.global) {
			this.r.lastIndex = pos;
			this.r.m = this.r.exec(len < 0 ? s : HxOverrides.substr(s,0,pos + len));
			var b = this.r.m != null;
			if(b) {
				this.r.s = s;
			}
			return b;
		} else {
			var b = this.match(len < 0 ? HxOverrides.substr(s,pos,null) : HxOverrides.substr(s,pos,len));
			if(b) {
				this.r.s = s;
				this.r.m.index += pos;
			}
			return b;
		}
	}
	,map: function(s,f) {
		var offset = 0;
		var buf_b = "";
		do {
			if(offset >= s.length) {
				break;
			} else if(!this.matchSub(s,offset)) {
				buf_b += Std.string(HxOverrides.substr(s,offset,null));
				break;
			}
			var p = this.matchedPos();
			buf_b += Std.string(HxOverrides.substr(s,offset,p.pos - offset));
			buf_b += Std.string(f(this));
			if(p.len == 0) {
				buf_b += Std.string(HxOverrides.substr(s,p.pos,1));
				offset = p.pos + 1;
			} else {
				offset = p.pos + p.len;
			}
		} while(this.r.global);
		if(!this.r.global && offset > 0 && offset < s.length) {
			buf_b += Std.string(HxOverrides.substr(s,offset,null));
		}
		return buf_b;
	}
};
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.now = function() {
	return Date.now();
};
Math.__name__ = true;
var Parser = function() { };
Parser.__name__ = true;
Parser.get = function(storydata) {
	var entry = "";
	var start = "";
	var startnode = storydata.getAttribute("startnode");
	var passages = storydata.children;
	var _g = 0;
	while(_g < passages.length) {
		var passage = passages[_g];
		++_g;
		var name = passage.getAttribute("name");
		var pid = passage.getAttribute("pid");
		if(name != null) {
			entry += "#" + name + "\n";
			if(pid == startnode) {
				start = name;
			}
			var content = passage.innerHTML.split("\n");
			var _g1 = 0;
			while(_g1 < content.length) {
				var line = content[_g1];
				++_g1;
				var string = StringTools.trim(line);
				var lead = string.substring(0,1);
				var link = string.substring(0,2);
				if(lead == "-") {
					string = StringTools.replace(string,"[[","");
					string = StringTools.replace(string,"]]","");
				}
				if(link == "[[") {
					string = StringTools.replace(string,"[[","");
					string = StringTools.replace(string,"]]","");
					string = "[move " + string + "]";
				}
				string = StringTools.replace(string,"&lt;","<");
				string = StringTools.replace(string,"&gt;",">");
				entry += string + "\n";
			}
		}
	}
	var story = harrow_Library.get(entry);
	story.move(start);
	return story;
};
var Render = function() { };
Render.__name__ = true;
Render.dice = function(name) {
	var value = parseFloat(harrow_Storage.get(name));
	if(isNaN(value)) {
		return "";
	}
	return "<dice><face></face><value>" + value + "</value></dice>";
};
Render.stat = function(name) {
	var value = parseFloat(harrow_Storage.get(name));
	if(isNaN(value)) {
		return "";
	}
	var upper = name.charAt(0).toUpperCase() + HxOverrides.substr(name,1,null);
	var label = upper.split(".").shift();
	return "<stat><bar><fill style=\"width:" + value + "%\"></fill></bar><label>" + label + ": " + value + "%</label></stat>";
};
Render.bar = function(name) {
	var upper = name.charAt(0).toUpperCase() + HxOverrides.substr(name,1,null);
	var label = upper.split(".").shift();
	var value = parseFloat(harrow_Storage.get(name));
	var total = parseFloat(harrow_Storage.get(name + ".max"));
	if(isNaN(value)) {
		return "";
	}
	if(isNaN(total) || total <= 0) {
		total = 100;
	}
	var percent = value / total * 100;
	return "<stat><bar><fill style=\"width:" + percent + "%\"></fill></bar><label>" + label + ": " + value + "/" + total + "</label></stat>";
};
var Settings = function(entry,data) {
	this.themeIndex = 0;
	this.themeValues = ["light","dark"];
	this.themeNames = ["Light","Dark"];
	this.fontFamilyIndex = 0;
	this.fontFamilyValues = ["sans-serif","serif"];
	this.fontFamilyNames = ["Default","Serif"];
	this.fontSizeIndex = 0;
	this.fontSizeValues = ["1em","1.3em","0.85em"];
	this.fontSizeNames = ["Default","Large","Small"];
	this.list = [];
	this.story = entry;
	this.fontFamilyValues[0] = window.getComputedStyle(window.document.body).fontFamily;
	var _g = 0;
	var _g1 = data.children;
	while(_g < _g1.length) {
		var passage = _g1[_g];
		++_g;
		var tags = passage.getAttribute("tags");
		if(tags == "menu") {
			this.list.push(passage.getAttribute("name"));
		}
	}
	if(this.list.length > 0) {
		this.list.push("Settings");
	}
	this.settings = window.document.querySelector("settings");
	this.textbox = window.document.querySelector("textbox");
};
Settings.__name__ = true;
Settings.prototype = {
	changeFontSize: function() {
		this.fontSizeIndex = (this.fontSizeIndex + 1) % this.fontSizeNames.length;
		this.textbox.style.fontSize = this.fontSizeValues[this.fontSizeIndex];
		this.updateSettingsLabels();
	}
	,changeFontFamily: function() {
		this.fontFamilyIndex = (this.fontFamilyIndex + 1) % this.fontFamilyNames.length;
		window.document.body.style.fontFamily = this.fontFamilyValues[this.fontFamilyIndex];
		this.updateSettingsLabels();
	}
	,changeTheme: function() {
		this.themeIndex = (this.themeIndex + 1) % this.themeNames.length;
		window.document.documentElement.setAttribute("data-theme",this.themeValues[this.themeIndex]);
		this.updateSettingsLabels();
	}
	,updateSettingsLabels: function() {
		this.sizeLabel.textContent = "Font Size: " + this.fontSizeNames[this.fontSizeIndex];
		this.familyLabel.textContent = "Font Family: " + this.fontFamilyNames[this.fontFamilyIndex];
		this.themeLabel.textContent = "Theme: " + this.themeNames[this.themeIndex];
	}
	,open: function() {
		var _gthis = this;
		window.document.querySelector("close").style.zIndex = "400";
		this.settings.innerHTML = "<header>" + Config.settings + "</header>";
		var menu = window.document.createElement("navigation");
		this.settings.appendChild(menu);
		var text = window.document.createElement("textbox");
		text.className = "information";
		this.settings.appendChild(text);
		var tabs = [];
		var _g = 0;
		var _g1 = this.list;
		while(_g < _g1.length) {
			var entry = [_g1[_g]];
			++_g;
			var tab = [window.document.createElement("div")];
			tab[0].className = "tab";
			tab[0].innerHTML = entry[0];
			tabs.push(tab[0]);
			tab[0].onclick = (function(tab,entry) {
				return function(event) {
					if(entry[0] == "Settings") {
						_gthis.getDefault(text);
					}
					if(entry[0] != "Settings") {
						text.innerHTML = _gthis.getRoute(entry[0]);
					}
					var _g = 0;
					while(_g < tabs.length) {
						var t = tabs[_g];
						++_g;
						t.className = "tab";
					}
					tab[0].className = "tab active";
				};
			})(tab,entry);
			menu.appendChild(tab[0]);
		}
		if(this.list.length == 0) {
			this.getDefault(text);
		}
		if(this.list.length != 0) {
			text.innerHTML = this.getRoute(this.list[0]);
		}
		if(tabs.length != 0) {
			tabs[0].className = "tab active";
		}
		this.settings.style.display = "grid";
		this.settings.style.zIndex = "300";
		this.settings.style.opacity = "1";
	}
	,close: function() {
		window.document.querySelector("close").style.zIndex = "-1";
		this.settings.removeAttribute("class");
		this.settings.style.display = "none";
		this.settings.style.opacity = "0";
		this.settings.style.zIndex = "-1";
	}
	,getDefault: function(element) {
		var _gthis = this;
		element.innerHTML = "";
		var letter = window.document.createElement("letter");
		letter.textContent = "A";
		var status = window.document.createElement("status");
		this.sizeLabel = window.document.createElement("size");
		this.sizeLabel.textContent = "Font Size: " + this.fontSizeNames[this.fontSizeIndex];
		this.sizeLabel.onclick = function(event) {
			_gthis.changeFontSize();
		};
		this.familyLabel = window.document.createElement("family");
		this.familyLabel.textContent = "Font Family: " + this.fontFamilyNames[this.fontFamilyIndex];
		this.familyLabel.onclick = function(event) {
			_gthis.changeFontFamily();
		};
		this.themeLabel = window.document.createElement("theme");
		this.themeLabel.textContent = "Theme: " + this.themeNames[this.themeIndex];
		this.themeLabel.onclick = function(e) {
			_gthis.changeTheme();
		};
		status.appendChild(this.sizeLabel);
		status.appendChild(this.familyLabel);
		status.appendChild(this.themeLabel);
		var divider = window.document.createElement("divider");
		var menu = window.document.createElement("menu");
		var restartItem = window.document.createElement("item");
		restartItem.textContent = "Restart the Game";
		restartItem.onclick = function(event) {
			window.location.reload();
		};
		var returnItem = window.document.createElement("item");
		returnItem.textContent = "Return";
		returnItem.onclick = function(event) {
			_gthis.close();
		};
		menu.appendChild(restartItem);
		menu.appendChild(returnItem);
		element.appendChild(letter);
		element.appendChild(status);
		element.appendChild(divider);
		element.appendChild(menu);
	}
	,getRoute: function(name) {
		var route = this.story.find("route",name);
		if(route == null) {
			return "";
		}
		var string = "";
		var hidden = null;
		var depth = 0;
		++route;
		var _g = route;
		var _g1 = this.story.data.length;
		while(_g < _g1) {
			var i = _g++;
			var page = this.story.data[i];
			if(page.type == "route") {
				break;
			}
			if(page.type == "condition") {
				if(page.data == "if") {
					++depth;
					if(hidden == null && !harrow_Logic.condition(page.text)) {
						hidden = depth;
					}
				} else if(page.text == "else") {
					if(hidden == depth) {
						hidden = null;
					} else if(hidden == null) {
						hidden = depth;
					}
				} else if(page.text == "end") {
					if(hidden == depth) {
						hidden = null;
					}
					--depth;
				}
			}
			if(hidden != null) {
				continue;
			}
			if(page.type == "text") {
				var speaker = page.data != "" ? "<span class=\"speaker\">" + page.data + "</span>" : "";
				var element = page.data != "" ? "<p class=\"" + page.data + "\">" : "<p>";
				if(!Config.speaker && page.data != "") {
					speaker = page.data + ": ";
				}
				string = string + element + speaker + harrow_Format.variable(page.text) + "</p>";
			}
			if(page.type == "event") {
				if(page.data == "stat") {
					string += Render.stat(page.text);
				}
				if(page.data == "bar") {
					string += Render.bar(page.text);
				}
			}
		}
		return string;
	}
};
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x);
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var StringTools = function() { };
StringTools.__name__ = true;
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	if(!(c > 8 && c < 14)) {
		return c == 32;
	} else {
		return true;
	}
};
StringTools.ltrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,r)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,r,l - r);
	} else {
		return s;
	}
};
StringTools.rtrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,l - r - 1)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,0,l - r);
	} else {
		return s;
	}
};
StringTools.trim = function(s) {
	return StringTools.ltrim(StringTools.rtrim(s));
};
StringTools.replace = function(s,sub,by) {
	return s.split(sub).join(by);
};
var harrow_Choice = function() {
	this.mode = "empty";
	this.data = "empty";
	this.text = "empty";
	this.type = "empty";
};
harrow_Choice.__name__ = true;
var harrow_Dialogue = function() { };
harrow_Dialogue.__name__ = true;
harrow_Dialogue.get = function(entry) {
	var map = entry.split("|");
	var choices = [];
	var _g = 0;
	var _g1 = map.length;
	while(_g < _g1) {
		var i = _g++;
		var key = map[i].split("::");
		var choice = new harrow_Choice();
		choice.text = key[0];
		choice.type = key[1];
		choice.data = key[2];
		choice.mode = key[3];
		choices.push(choice);
	}
	return choices;
};
var harrow_Format = function() { };
harrow_Format.__name__ = true;
harrow_Format.variable = function(entry) {
	if(entry.indexOf("[") == -1) {
		return entry;
	}
	var rex = new EReg("\\[(.*?)\\]","g");
	entry = rex.map(entry,function(r) {
		var matching = r.matched(0);
		var variable = matching.substring(1,matching.length - 1);
		if(harrow_Storage.has(variable)) {
			return harrow_Storage.get(variable);
		}
		console.log("src/harrow/Format.hx:15:","Warning: variable \"" + variable + "\" is not defined");
		return matching;
	});
	return entry;
};
harrow_Format.string = function(entry) {
	return StringTools.replace(entry,":"," ");
};
var harrow_Library = function() { };
harrow_Library.__name__ = true;
harrow_Library.get = function(entry,validate) {
	if(validate == null) {
		validate = true;
	}
	var res = entry.split("\n");
	var story = new harrow_Story();
	var last = null;
	var _g = 0;
	while(_g < res.length) {
		var line = res[_g];
		++_g;
		var page = harrow_Library.parse(line);
		var skip = harrow_Library.merge(page,last);
		if(page == null) {
			last = null;
		}
		if(page == null) {
			skip = true;
		}
		if(skip == false) {
			story.data.push(page);
			last = page;
		}
	}
	if(validate) {
		harrow_Syntax.validate(story);
	}
	return story;
};
harrow_Library.parse = function(entry) {
	var string = StringTools.trim(entry);
	if(string.length == 0) {
		return null;
	}
	if(string.substring(0,1) == "/") {
		return null;
	}
	var page = new harrow_Page();
	page.type = "text";
	var leading = string.substring(0,1);
	if(leading == "#") {
		page.type = "route";
	}
	if(leading == "-") {
		page.type = harrow_Library.getDialogue(string);
	}
	if(leading == "[") {
		page.type = harrow_Library.getEvent(string);
	}
	switch(page.type) {
	case "dialogue":
		harrow_Library.setDialogue(page,string);
		break;
	case "event":
		harrow_Library.setEvent(page,string);
		break;
	case "route":
		harrow_Library.setRoute(page,string);
		break;
	case "text":
		harrow_Library.setText(page,string);
		break;
	}
	harrow_Syntax.custom(page,string);
	return page;
};
harrow_Library.merge = function(page,last) {
	if(page != null && page.type == "dialogue" && last != null && last.type == "dialogue") {
		last.text = last.text + "|" + page.text;
		last.data = "dialogue";
		return true;
	}
	return false;
};
harrow_Library.setText = function(page,entry) {
	var raw = StringTools.replace(entry,harrow_Library.ESCAPE,harrow_Library.DIVIDE);
	var key = raw.indexOf(":");
	page.text = key >= 0 ? StringTools.trim(HxOverrides.substr(raw,key + 1,null)) : raw;
	page.data = key >= 0 ? StringTools.trim(HxOverrides.substr(raw,0,key)) : "";
	page.text = StringTools.replace(page.text,harrow_Library.DIVIDE,":");
	var open = page.data.indexOf("<");
	var close = page.data.indexOf(">");
	if(open != -1 && close > open) {
		page.tags = HxOverrides.substr(page.data,open + 1,close - open - 1);
		page.data = HxOverrides.substr(page.data,0,open);
	}
};
harrow_Library.setRoute = function(page,entry) {
	var locked = entry.substring(0,2) != "#" + "#";
	page.text = StringTools.trim(StringTools.replace(entry,"#",""));
	page.data = locked ? "route" : "label";
};
harrow_Library.setDialogue = function(page,entry) {
	var res = entry.substring(1);
	var key = res.split(":");
	var text = StringTools.trim(key[harrow_Library.TYPE]);
	var type = "empty";
	var data = "empty";
	var mode = "empty";
	if(key.length > 1) {
		var string = StringTools.trim(key[harrow_Library.TEXT]);
		string = StringTools.replace(string," ",":");
		var prop = string.split(":");
		if(harrow_Library.isVariable(prop[harrow_Library.TEXT])) {
			type = "variable";
			data = string;
		} else {
			type = "route";
			data = StringTools.trim(key[harrow_Library.TEXT]);
		}
	}
	if(key.length > 2) {
		mode = StringTools.trim(key[harrow_Library.DATA]);
		mode = StringTools.replace(mode," ",":");
	}
	page.text = text + "::" + type + "::" + data + "::" + mode;
	page.data = "button";
};
harrow_Library.setEvent = function(page,entry) {
	var string = entry.substring(1,entry.length - 1);
	string = StringTools.trim(string);
	string = StringTools.replace(string," " + " ",":");
	string = StringTools.replace(string," ",":");
	var key = string.split(":");
	var type = key[harrow_Library.TYPE];
	page.type = "event";
	page.text = StringTools.replace(string,type + ":","");
	page.data = type;
	if(type == "story" || type == "move") {
		page.type = "move";
		page.text = StringTools.replace(page.text,":"," ");
	}
	if(type == "lock" || type == "close") {
		page.type = "move";
	}
	if(type == "if") {
		page.type = "condition";
		page.text = StringTools.replace(string,"if:","");
	}
	if(type == "else" || type == "end") {
		page.type = "condition";
		page.text = type;
	}
	if(harrow_Library.isVariable(key[harrow_Library.TEXT])) {
		page.type = "variable";
		page.text = string;
	}
};
harrow_Library.getDialogue = function(entry) {
	if(entry.length >= 2 && entry.substring(0,2) == "-" + "-") {
		return "break";
	}
	return "dialogue";
};
harrow_Library.getEvent = function(entry) {
	if(entry.indexOf("]") != entry.length - 1) {
		return "text";
	}
	return "event";
};
harrow_Library.isVariable = function(entry) {
	return harrow_Logic.operators.indexOf(entry) != -1;
};
var harrow_Logic = function() { };
harrow_Logic.__name__ = true;
harrow_Logic.variable = function(entry) {
	var key = entry.split(":");
	var name = key.shift();
	var type = key.shift();
	var prop = key.join(" ");
	if(type != null) {
		switch(type) {
		case "%":
			var a = harrow_Logic.float(name);
			var b = harrow_Logic.float(prop);
			harrow_Logic.set(name,Std.string(a % b));
			break;
		case "%+":
			var old = harrow_Logic.float(name);
			var pct = harrow_Logic.float(prop);
			var value = old + (100 - old) * pct / 100;
			harrow_Logic.set(name,Std.string(harrow_Logic.clamp(value,0,100)));
			break;
		case "%-":
			var old = harrow_Logic.float(name);
			var pct = harrow_Logic.float(prop);
			var value = old - old * pct / 100;
			harrow_Logic.set(name,Std.string(harrow_Logic.clamp(value,0,100)));
			break;
		case "*":
			var a = harrow_Logic.float(name);
			var b = harrow_Logic.float(prop);
			harrow_Logic.set(name,Std.string(a * b));
			break;
		case "+":
			var a = harrow_Logic.float(name);
			var b = harrow_Logic.float(prop);
			harrow_Logic.set(name,Std.string(a + b));
			break;
		case "-":
			var a = harrow_Logic.float(name);
			var b = harrow_Logic.float(prop);
			harrow_Logic.set(name,Std.string(a - b));
			break;
		case "/":
			var a = harrow_Logic.float(name);
			var b = harrow_Logic.float(prop);
			harrow_Logic.set(name,Std.string(a / b));
			break;
		case "=":
			harrow_Logic.set(name,harrow_Logic.string(prop));
			break;
		case "chance":
			var prob = harrow_Random.chance(harrow_Logic.string(prop));
			harrow_Logic.set(name,prob == null ? "null" : "" + prob);
			break;
		case "roll":
			var roll = harrow_Random.dice(harrow_Logic.string(prop));
			harrow_Logic.set(name,roll == null ? "null" : "" + roll);
			break;
		default:
		}
	}
};
harrow_Logic.condition = function(entry) {
	if(entry == "else") {
		return false;
	}
	if(entry == "end") {
		return true;
	}
	var key = entry.split(":");
	var name = key.shift();
	var type = key.shift();
	var prop = key.join(" ");
	var result = false;
	if(type != null) {
		switch(type) {
		case "!=":
			result = harrow_Logic.string(name) != harrow_Logic.string(prop);
			break;
		case "<":
			var a = harrow_Logic.float(name);
			var b = harrow_Logic.float(prop);
			result = a < b;
			break;
		case "<=":
			var a = harrow_Logic.float(name);
			var b = harrow_Logic.float(prop);
			result = a <= b;
			break;
		case "=":case "==":case "is":
			result = harrow_Logic.string(name) == harrow_Logic.string(prop);
			break;
		case ">":
			var a = harrow_Logic.float(name);
			var b = harrow_Logic.float(prop);
			result = a > b;
			break;
		case ">=":
			var a = harrow_Logic.float(name);
			var b = harrow_Logic.float(prop);
			result = a >= b;
			break;
		case "chance":
			result = harrow_Random.chance(harrow_Logic.string(prop));
			break;
		default:
		}
	}
	return result;
};
harrow_Logic.clamp = function(v,min,max) {
	if(v < min) {
		return min;
	}
	if(v > max) {
		return max;
	}
	return v;
};
harrow_Logic.float = function(entry) {
	var number = parseFloat(harrow_Logic.string(entry));
	if(isNaN(number)) {
		console.log("src/harrow/Logic.hx:123:","Warning: \"" + entry + "\" is not a number, defaulting to 0");
		return 0;
	}
	return number;
};
harrow_Logic.string = function(entry) {
	if(entry == "false" || entry == "true") {
		return entry;
	}
	if(harrow_Storage.has(entry)) {
		return harrow_Storage.get(entry);
	}
	return entry;
};
harrow_Logic.set = function(entry,value) {
	harrow_Storage.set(entry,value);
};
var harrow_Page = function() {
	this.tags = "";
	this.data = "";
	this.text = "";
	this.type = "";
};
harrow_Page.__name__ = true;
var harrow_Random = function() { };
harrow_Random.__name__ = true;
harrow_Random.chance = function(entry) {
	return harrow_Random.roll(0,100) < Std.parseInt(entry);
};
harrow_Random.dice = function(entry) {
	return harrow_Random.roll(1,Std.parseInt(entry));
};
harrow_Random.roll = function(min,max) {
	return min + Math.floor((max - min + 1) * Math.random());
};
var harrow_Runtime = function(entry) {
	this.story = entry;
};
harrow_Runtime.__name__ = true;
harrow_Runtime.prototype = {
	nextPage: function() {
		if(this.story.get_end()) {
			this.onEnd();
		}
		if(this.story.get_end()) {
			return;
		}
		this.page = this.story.next();
		this.onPage(this.page);
		switch(this.page.type) {
		case "break":
			this.nextPage();
			break;
		case "condition":
			var condition = harrow_Logic.condition(this.page.text);
			if(condition == false) {
				this.story.skip();
			}
			this.nextPage();
			break;
		case "dialogue":
			var dialogue = harrow_Dialogue.get(this.page.text);
			var _g = 0;
			while(_g < dialogue.length) {
				var choice = dialogue[_g];
				++_g;
				choice.text = harrow_Format.variable(choice.text);
			}
			this.onDialogue(dialogue);
			break;
		case "event":
			this.gameEvent();
			break;
		case "move":
			if(this.page.data == "story") {
				this.onStory(this.page.text);
			}
			if(this.page.data == "close") {
				this.onClose();
			}
			if(this.page.data == "lock") {
				this.onLock();
			}
			if(this.page.data == "move") {
				this.story.move(this.page.text);
				this.nextPage();
			}
			break;
		case "route":
			if(this.page.data == "label") {
				this.nextPage();
			}
			break;
		case "text":
			var text = harrow_Format.variable(this.page.text);
			this.onText(text,this.page.data);
			break;
		case "variable":
			harrow_Logic.variable(this.page.text);
			this.nextPage();
			break;
		default:
		}
	}
	,gameEvent: function() {
		switch(this.page.data) {
		case "transition":
			this.onTransition(this.page.text);
			break;
		case "wait":
			var time = Std.parseInt(this.page.text);
			haxe_Timer.delay($bind(this,this.nextPage),time * 60);
			break;
		default:
			this.onEvent(this.page.data,this.page.text);
			this.nextPage();
		}
	}
	,onPage: function(page) {
	}
	,onText: function(text,name) {
	}
	,onDialogue: function(dialogue) {
	}
	,onEvent: function(type,data) {
	}
	,onTransition: function(name) {
	}
	,onStory: function(name) {
	}
	,onClose: function() {
	}
	,onLock: function() {
	}
	,onEnd: function() {
	}
};
var haxe_ds_StringMap = function() {
	this.h = Object.create(null);
};
haxe_ds_StringMap.__name__ = true;
var harrow_Storage = function() { };
harrow_Storage.__name__ = true;
harrow_Storage.get = function(key) {
	return harrow_Storage.variable.h[key];
};
harrow_Storage.set = function(key,value) {
	harrow_Storage.variable.h[key] = value;
};
harrow_Storage.has = function(key) {
	return Object.prototype.hasOwnProperty.call(harrow_Storage.variable.h,key);
};
var harrow_Story = function() {
	this.page = -1;
	this.data = [];
};
harrow_Story.__name__ = true;
harrow_Story.prototype = {
	next: function() {
		if(this.page < this.data.length) {
			this.page += 1;
		}
		return this.data[this.page];
	}
	,move: function(route) {
		var _g = 0;
		var _g1 = this.data.length;
		while(_g < _g1) {
			var i = _g++;
			if(this.data[i].type == "route" && this.data[i].text == route) {
				return this.page = i;
			}
		}
		return this.page;
	}
	,skip: function() {
		var position = this.page + 1;
		var depth = 0;
		var _g = position;
		var _g1 = this.data.length;
		while(_g < _g1) {
			var i = _g++;
			if(this.data[i].type == "condition") {
				if(this.data[i].data == "if") {
					++depth;
				}
				if(this.data[i].text == "end" || this.data[i].text == "else") {
					if(depth == 0) {
						return this.page = i;
					}
					if(this.data[i].text == "end") {
						--depth;
					}
				}
			}
		}
		return this.page;
	}
	,turn: function(number) {
		if(number < 0 || number > this.data.length - 1) {
			return this.page;
		}
		return this.page = number;
	}
	,look: function(number) {
		if(number < 0 || number > this.data.length - 1) {
			return null;
		}
		return this.data[number];
	}
	,find: function(type,text) {
		var _g = 0;
		var _g1 = this.data.length;
		while(_g < _g1) {
			var i = _g++;
			if(this.data[i].type == type && this.data[i].text == text) {
				return i;
			}
		}
		return null;
	}
	,get_end: function() {
		return this.page == this.data.length - 1;
	}
};
var harrow_Syntax = function() { };
harrow_Syntax.__name__ = true;
harrow_Syntax.customSyntax = function(page,entry) {
};
harrow_Syntax.validate = function(story) {
	var variables_h = Object.create(null);
	var duplicates_h = Object.create(null);
	var routes_h = Object.create(null);
	var _g = 0;
	var _g1 = story.data;
	while(_g < _g1.length) {
		var page = _g1[_g];
		++_g;
		if(page.type == "variable") {
			var parts = page.text.split(":");
			var name = parts[0];
			var type = parts[1];
			if(type == "=" || type == "roll" || type == "chance") {
				if(!harrow_Syntax.isValidName(name)) {
					throw haxe_Exception.thrown("Invalid variable name \"" + name + "\"");
				}
				variables_h[name] = true;
			}
		}
		if(page.type == "route" && page.data == "route") {
			routes_h[page.text] = false;
		}
		if(page.type == "route") {
			var name1 = page.text;
			var count = Object.prototype.hasOwnProperty.call(duplicates_h,name1) ? duplicates_h[name1] + 1 : 1;
			duplicates_h[name1] = count;
		}
	}
	var _g = 0;
	var _g1 = story.data;
	while(_g < _g1.length) {
		var page = _g1[_g];
		++_g;
		switch(page.type) {
		case "condition":
			if(page.data == "if") {
				if(page.text.split(":").length < 3) {
					console.log("src/harrow/Syntax.hx:99:","Warning: Invalid input format: \"" + page.text + "\". Expected: name:operator:value");
				}
			}
			break;
		case "dialogue":
			var lines = page.text.split("|");
			var _g2 = 0;
			while(_g2 < lines.length) {
				var line = lines[_g2];
				++_g2;
				var parts = line.split("::");
				if(parts.length >= 3 && parts[1] == "route") {
					var target = parts[2];
					if(Object.prototype.hasOwnProperty.call(routes_h,target)) {
						routes_h[target] = true;
					} else {
						console.log("src/harrow/Syntax.hx:78:","Warning: Reference to undefined route \"" + target + "\"");
					}
				}
				if(parts.length >= 3 && parts[1] == "variable") {
					var expr = parts[2].split(":");
					var name = expr[0];
					var type = expr[1];
					if(harrow_Syntax.OPERATOR.indexOf(type) != -1) {
						if(!Object.prototype.hasOwnProperty.call(variables_h,name)) {
							console.log("src/harrow/Syntax.hx:90:","Warning: Variable \"" + name + "\" is not defined (used in dialogue choice)");
						}
					}
				}
			}
			break;
		case "move":
			if(page.data == "move") {
				if(Object.prototype.hasOwnProperty.call(routes_h,page.text)) {
					routes_h[page.text] = true;
				} else {
					console.log("src/harrow/Syntax.hx:63:","Warning: Reference to undefined route \"" + page.text + "\"");
				}
			}
			break;
		case "variable":
			var parts1 = page.text.split(":");
			if(parts1.length < 3) {
				console.log("src/harrow/Syntax.hx:107:","Warning: Invalid input format: \"" + page.text + "\". Expected: name:operator:value");
			}
			var name1 = parts1[0];
			var type1 = parts1[1];
			if(harrow_Syntax.OPERATOR.indexOf(type1) != -1) {
				if(!Object.prototype.hasOwnProperty.call(variables_h,name1)) {
					console.log("src/harrow/Syntax.hx:116:","Warning: Variable \"" + name1 + "\" is not defined");
				}
			}
			break;
		default:
		}
	}
	var h = duplicates_h;
	var _g_h = h;
	var _g_keys = Object.keys(h);
	var _g_length = _g_keys.length;
	var _g_current = 0;
	while(_g_current < _g_length) {
		var key = _g_keys[_g_current++];
		var _g_key = key;
		var _g_value = _g_h[key];
		var route = _g_key;
		var count = _g_value;
		if(count > 1) {
			console.log("src/harrow/Syntax.hx:126:","Warning: Duplicate route \"" + route + "\" (appears " + count + " times)");
		}
	}
	var h = routes_h;
	var _g_h = h;
	var _g_keys = Object.keys(h);
	var _g_length = _g_keys.length;
	var _g_current = 0;
	while(_g_current < _g_length) {
		var key = _g_keys[_g_current++];
		var _g_key = key;
		var _g_value = _g_h[key];
		var route = _g_key;
		var reference = _g_value;
		if(!reference) {
			console.log("src/harrow/Syntax.hx:131:","Warning: Route \"" + route + "\" may be unreachable");
		}
	}
};
harrow_Syntax.isValidName = function(name) {
	if(name == null || name.length == 0) {
		return false;
	}
	var f = parseFloat(name);
	if(!isNaN(f)) {
		return false;
	}
	if(harrow_Syntax.RESERVED.indexOf(name) != -1) {
		return false;
	}
	var first = name.charAt(0);
	if(!(first >= "a" && first <= "z")) {
		if(first >= "A") {
			return first <= "Z";
		} else {
			return false;
		}
	} else {
		return true;
	}
};
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	get_native: function() {
		return this.__nativeException;
	}
});
var haxe_Timer = function(time_ms) {
	var me = this;
	this.id = setInterval(function() {
		me.run();
	},time_ms);
};
haxe_Timer.__name__ = true;
haxe_Timer.delay = function(f,time_ms) {
	var t = new haxe_Timer(time_ms);
	t.run = function() {
		t.stop();
		f();
	};
	return t;
};
haxe_Timer.prototype = {
	stop: function() {
		if(this.id == null) {
			return;
		}
		clearInterval(this.id);
		this.id = null;
	}
	,run: function() {
	}
};
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
});
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var $_;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
String.__name__ = true;
Array.__name__ = true;
js_Boot.__toStr = ({ }).toString;
Config.settings = "Settings";
Config.endText = "<h2 style=\"text-align: center;\">The End.</h2>";
Config.speaker = false;
Config.fadeText = true;
Config.fadeImage = true;
Config.maxHeight = 80;
Config.maxVertical = 3;
Config.folder = "";
harrow_Library.DIVIDE = "";
harrow_Library.ESCAPE = "\\:";
harrow_Library.TYPE = 0;
harrow_Library.TEXT = 1;
harrow_Library.DATA = 2;
harrow_Logic.operators = ["=","+","-","*","/","%","roll","chance","%+","%-"];
harrow_Storage.variable = new haxe_ds_StringMap();
harrow_Syntax.RESERVED = ["true","false","else","end","chance","roll"];
harrow_Syntax.OPERATOR = ["=","+","-","*","/","%","%+","%-"];
harrow_Syntax.custom = harrow_Syntax.customSyntax;
App.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
