// Generated by Haxe 4.3.4
(function ($hx_exports, $global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var App = $hx_exports["App"] = function() {
	this.folder = "";
	this.buffer = "";
	this.maxlenght = 240;
	this.parsespeaker = false;
	this.bookmark = [];
	var _gthis = this;
	harrow_Library.parseSpeaker = true;
	harrow_Logic.random = new Dice();
	var storydata = window.document.querySelector("tw-storydata");
	this.story = Parser.get(storydata);
	this.novel = new harrow_Runtime(this.story);
	this.novel.onText = $bind(this,this.onText);
	this.novel.onDialogue = $bind(this,this.onDialogue);
	this.novel.onTransition = $bind(this,this.onTransition);
	this.novel.onEvent = $bind(this,this.onEvent);
	this.novel.onEnd = $bind(this,this.onEnd);
	this.textbox = window.document.querySelector("textbox");
	this.dialogue = window.document.querySelector("dialogue");
	this.button = window.document.querySelector("button");
	this.button.textContent = "Continue";
	this.button.style.display = "none";
	this.button.onclick = function(event) {
		_gthis.onClick();
	};
	window.document.querySelector("chapter").innerHTML = storydata.getAttribute("name");
	window.document.querySelector("close").onclick = function(event) {
		_gthis.close();
	};
	window.document.querySelector("open").onclick = function(event) {
		_gthis.open("Settings");
	};
	var style = window.document.createElement("style");
	style.innerHTML = window.document.querySelector("#twine-user-stylesheet").innerHTML;
	window.document.querySelector("body").appendChild(style);
	var script = window.document.createElement("script");
	script.innerHTML = window.document.querySelector("#twine-user-script").innerHTML;
	window.document.querySelector("body").appendChild(script);
	this.novel.nextPage();
};
App.__name__ = true;
App.main = function() {
	App.ME = new App();
};
App.prototype = {
	onClick: function() {
		this.button.style.display = "none";
		this.novel.nextPage();
	}
	,showText: function() {
		this.textbox.innerHTML = this.buffer;
		this.buffer = "";
		this.textbox.style.opacity = "0";
		$(this.textbox).fadeTo(300,1);
	}
	,onText: function(text,name) {
		var speaker = name != "" ? "<span class = \"speaker\">" + name + "</span>" : "";
		var element = name != "" ? "<p class = \"" + name + "\">" : "<p>";
		if(!this.parsespeaker && name != "") {
			speaker = name + ": ";
		}
		this.buffer = this.buffer + element + speaker + this.decode(text) + "</p>";
		var ready = this.buffer.length > this.maxlenght;
		var page = this.novel.story.look(this.novel.story.page + 1);
		var last = page == null;
		if(last) {
			this.button.style.display = "block";
			this.showText();
		}
		if(last) {
			return;
		}
		if(page.type == "dialogue" && ready) {
			this.novel.nextPage();
		}
		if(page.type != "dialogue" && ready) {
			this.button.style.display = "block";
			this.showText();
		}
		if(ready) {
			return;
		}
		if(page.type == "text" || page.type == "dialogue") {
			this.novel.nextPage();
		} else {
			this.button.style.display = "block";
			this.showText();
		}
	}
	,onDialogue: function(choices) {
		var _gthis = this;
		if(this.buffer.length > 0) {
			this.showText();
		}
		var _g = 0;
		while(_g < choices.length) {
			var entry = [choices[_g]];
			++_g;
			var choice = window.document.createElement("choice");
			choice.setAttribute("role","button");
			choice.innerHTML = this.format(entry[0].text);
			if(entry[0].role != "empty") {
				choice.id = entry[0].role;
			}
			var allowed = entry[0].mode == "empty" ? true : harrow_Logic.condition(entry[0].mode);
			if(!allowed) {
				choice.className = "disabled";
			}
			choice.onclick = (function(entry) {
				return function(event) {
					_gthis.onSelect(entry[0].type,entry[0].data);
				};
			})(entry);
			this.dialogue.appendChild(choice);
		}
	}
	,onSelect: function(type,data) {
		this.dialogue.innerHTML = "";
		this.textbox.innerHTML = "";
		this.novel.onChoice(type,data);
	}
	,onEvent: function(type,data) {
		switch(type) {
		case "config.assets.folder":
			this.folder = data;
			break;
		case "config.parse.speaker":
			this.parsespeaker = data == "true";
			break;
		case "config.text.maxlenght":
			this.maxlenght = Std.parseInt(data);
			break;
		case "image":
			this.imageEvent(data);
			break;
		case "scene":
			this.sceneEvent(data);
			this.novel.nextPage();
			break;
		default:
			this.screenEvent(type,data);
		}
	}
	,sceneEvent: function(data) {
		if(data == "close") {
			var page = this.bookmark.pop();
			if(page != null) {
				this.story.turn(page);
			}
		} else if(data == "clear") {
			this.bookmark = [];
		} else {
			this.bookmark.push(this.story.page);
			this.story.move(data);
		}
	}
	,imageEvent: function(data) {
		var element = window.document.querySelector("imagebox");
		if(data == "show") {
			window.document.querySelector("page").className = "novel";
			element.style.display = "block";
		} else if(data == "hide") {
			window.document.querySelector("page").removeAttribute("class");
			element.style.display = "none";
		} else {
			window.document.querySelector("page").className = "novel";
			element.style.display = "block";
			var tmp = "url('" + this.folder + this.decode(data);
			element.style.backgroundImage = tmp + "')";
			element.style.opacity = "0";
			$(element).fadeTo(300,1);
		}
	}
	,screenEvent: function(name,data) {
		var entry = data.split(":");
		var type = entry.shift();
		var text = entry.join(" ");
		var element = window.document.querySelector(name);
		if(element == null) {
			return;
		}
		text = this.decode(text);
		if(type != null) {
			switch(type) {
			case "add":
				var item = window.document.createElement(text);
				element.appendChild(item);
				break;
			case "after":
				var item = window.document.createElement(text);
				element.parentNode.insertBefore(item,element.nextSibling);
				break;
			case "append":
				element.innerHTML += this.format(text);
				break;
			case "before":
				var item = window.document.createElement(text);
				element.parentNode.insertBefore(item,element);
				break;
			case "class":
				element.setAttribute("class",text);
				if(text == "default") {
					element.removeAttribute("class");
				}
				break;
			case "css":
				var position = text.indexOf(" ");
				var prop = text.substring(0,position);
				var data = text.substring(position + 1,text.length);
				element.style.setProperty(prop,data);
				break;
			case "hide":
				element.style.display = "none";
				break;
			case "html":
				element.innerHTML = text == "empty" ? "" : this.format(text);
				break;
			case "id":
				element.setAttribute("id",text);
				if(text == "default") {
					element.removeAttribute("id");
				}
				break;
			case "image":
				element.style.backgroundImage = "url('" + this.folder + text + "')";
				element.style.opacity = "0";
				$(element).fadeTo(300,1);
				break;
			case "onclick":
				element.setAttribute("onclick",this.format(text));
				break;
			case "remove":
				element.parentNode.removeChild(element);
				break;
			case "show":
				element.style.display = "block";
				break;
			case "text":
				element.textContent = text == "empty" ? "" : this.format(text);
				break;
			default:
			}
		}
	}
	,onTransition: function() {
		var _gthis = this;
		var hide = function() {
			var transition = window.document.querySelector("transition");
			transition.style.zIndex = "-1";
		};
		var fade = function() {
			var transition = window.document.querySelector("transition");
			transition.className = "off";
			haxe_Timer.delay(hide,600);
			_gthis.novel.nextPage();
		};
		var transition = window.document.querySelector("transition");
		transition.style.zIndex = "600";
		transition.className = "active";
		haxe_Timer.delay(fade,900);
	}
	,onEnd: function() {
		this.textbox.innerHTML = "<p>Story End.</p>";
		$(this.textbox).fadeTo(300,1);
	}
	,open: function(name) {
		var page = this.story.find("route",name);
		if(page == null) {
			return;
		}
		var skip = false;
		var string = "";
		++page;
		var _g = page;
		var _g1 = this.story.data.length;
		while(_g < _g1) {
			var i = _g++;
			if(this.story.data[i].type == "route") {
				break;
			}
			if(this.story.data[i].type == "condition") {
				if(skip && this.story.data[i].text == "else" || skip && this.story.data[i].text == "end") {
					skip = false;
				} else {
					skip = !harrow_Logic.condition(this.story.data[i].text);
				}
			}
			if(skip) {
				continue;
			}
			if(this.story.data[i].type == "text") {
				var speaker = this.story.data[i].data;
				var element = speaker != "" ? "<p class = \"" + speaker + "\">" : "<p>";
				string = string + element + this.story.data[i].text + "</p>";
			}
			if(this.story.data[i].type == "event") {
				var element1 = StringTools.replace(this.story.data[i].text,":"," ");
				element1 = this.story.data[i].data + " " + this.decode(element1);
				element1 = this.format(element1);
				string += element1;
			}
		}
		window.document.querySelector("close").style.zIndex = "400";
		var element = window.document.querySelector("settings");
		element.innerHTML = "<content>" + string + "</content>";
		element.setAttribute("class",name.toLowerCase());
		element.style.display = "grid";
		element.style.zIndex = "300";
		element.style.opacity = "1";
	}
	,close: function() {
		window.document.querySelector("close").style.zIndex = "-1";
		var element = window.document.querySelector("settings");
		element.removeAttribute("class");
		element.style.display = "none";
		element.style.opacity = "0";
		element.style.zIndex = "-1";
	}
	,get: function(key) {
		return harrow_Storage.get(key);
	}
	,set: function(key,value) {
		harrow_Storage.set(key,value);
	}
	,decode: function(entry) {
		entry = StringTools.replace(entry,"https ","https:");
		entry = StringTools.replace(entry,"http ","http:");
		return entry;
	}
	,format: function(entry) {
		if(entry.indexOf("$") == -1) {
			return entry;
		}
		var rex = new EReg("\\$\\S+?(?=[^a-zA-Z.]|$)","g");
		entry = rex.map(entry,function(r) {
			var matching = r.matched(0);
			var variable = matching.substring(1,matching.length);
			if(harrow_Storage.has(variable)) {
				return harrow_Storage.get(variable);
			}
			return matching;
		});
		return entry;
	}
};
var harrow_Random = function() {
};
harrow_Random.__name__ = true;
harrow_Random.prototype = {
	chance: function(entry) {
		return this.roll(0,100) < Std.parseInt(entry);
	}
	,dice: function(entry) {
		return this.roll(1,Std.parseInt(entry));
	}
	,roll: function(min,max) {
		return min + Math.floor((max - min + 1) * Math.random());
	}
};
var Dice = function() {
	harrow_Random.call(this);
};
Dice.__name__ = true;
Dice.__super__ = harrow_Random;
Dice.prototype = $extend(harrow_Random.prototype,{
	dice: function(entry) {
		var text = entry.toLowerCase();
		var keys = text.split("d");
		if(keys.length == 1) {
			return this.roll(1,Std.parseInt(text));
		}
		var pool = Std.parseInt(keys.shift());
		var side = keys.shift();
		var type = side.charAt(side.length - 1);
		if(type == "h" || type == "l") {
			side = side.substring(0,side.length - 1);
		}
		var rolls = [];
		var total = 0;
		var _g = 0;
		var _g1 = pool;
		while(_g < _g1) {
			var i = _g++;
			var take = this.roll(1,Std.parseInt(side));
			total += take;
			rolls.push(take);
		}
		rolls.sort(function(a,b) {
			return a - b;
		});
		if(type == "l") {
			return rolls.shift();
		}
		if(type == "h") {
			return rolls.pop();
		}
		return total;
	}
});
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
EReg.__name__ = true;
EReg.prototype = {
	match: function(s) {
		if(this.r.global) {
			this.r.lastIndex = 0;
		}
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		if(this.r.m != null && n >= 0 && n < this.r.m.length) {
			return this.r.m[n];
		} else {
			throw haxe_Exception.thrown("EReg::matched");
		}
	}
	,matchedPos: function() {
		if(this.r.m == null) {
			throw haxe_Exception.thrown("No string matched");
		}
		return { pos : this.r.m.index, len : this.r.m[0].length};
	}
	,matchSub: function(s,pos,len) {
		if(len == null) {
			len = -1;
		}
		if(this.r.global) {
			this.r.lastIndex = pos;
			this.r.m = this.r.exec(len < 0 ? s : HxOverrides.substr(s,0,pos + len));
			var b = this.r.m != null;
			if(b) {
				this.r.s = s;
			}
			return b;
		} else {
			var b = this.match(len < 0 ? HxOverrides.substr(s,pos,null) : HxOverrides.substr(s,pos,len));
			if(b) {
				this.r.s = s;
				this.r.m.index += pos;
			}
			return b;
		}
	}
	,map: function(s,f) {
		var offset = 0;
		var buf_b = "";
		do {
			if(offset >= s.length) {
				break;
			} else if(!this.matchSub(s,offset)) {
				buf_b += Std.string(HxOverrides.substr(s,offset,null));
				break;
			}
			var p = this.matchedPos();
			buf_b += Std.string(HxOverrides.substr(s,offset,p.pos - offset));
			buf_b += Std.string(f(this));
			if(p.len == 0) {
				buf_b += Std.string(HxOverrides.substr(s,p.pos,1));
				offset = p.pos + 1;
			} else {
				offset = p.pos + p.len;
			}
		} while(this.r.global);
		if(!this.r.global && offset > 0 && offset < s.length) {
			buf_b += Std.string(HxOverrides.substr(s,offset,null));
		}
		return buf_b;
	}
};
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.now = function() {
	return Date.now();
};
Math.__name__ = true;
var Parser = function() { };
Parser.__name__ = true;
Parser.get = function(storydata) {
	var entry = "";
	var start = "";
	var startnode = storydata.getAttribute("startnode");
	var passages = storydata.children;
	var _g = 0;
	while(_g < passages.length) {
		var passage = passages[_g];
		++_g;
		var name = passage.getAttribute("name");
		var pid = passage.getAttribute("pid");
		if(name != null) {
			entry += "#" + name + "\n";
			if(pid == startnode) {
				start = name;
			}
			var content = passage.innerHTML.split("\n");
			var _g1 = 0;
			while(_g1 < content.length) {
				var line = content[_g1];
				++_g1;
				var string = StringTools.trim(line);
				var lead = string.substring(0,1);
				var link = string.substring(0,2);
				if(lead == "-") {
					string = StringTools.replace(string,"[[","");
					string = StringTools.replace(string,"]]","");
				}
				if(link == "[[") {
					string = StringTools.replace(string,"[[","");
					string = StringTools.replace(string,"]]","");
					string = "[move " + string + "]";
				}
				string = StringTools.replace(string,"&lt;","<");
				string = StringTools.replace(string,"&gt;",">");
				entry += string + "\n";
			}
		}
	}
	var story = harrow_Library.get(entry);
	story.move(start);
	return story;
};
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x);
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var StringTools = function() { };
StringTools.__name__ = true;
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	if(!(c > 8 && c < 14)) {
		return c == 32;
	} else {
		return true;
	}
};
StringTools.ltrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,r)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,r,l - r);
	} else {
		return s;
	}
};
StringTools.rtrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,l - r - 1)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,0,l - r);
	} else {
		return s;
	}
};
StringTools.trim = function(s) {
	return StringTools.ltrim(StringTools.rtrim(s));
};
StringTools.replace = function(s,sub,by) {
	return s.split(sub).join(by);
};
var harrow_Choice = function() {
	this.role = "empty";
	this.mode = "empty";
	this.data = "empty";
	this.text = "empty";
	this.type = "empty";
};
harrow_Choice.__name__ = true;
var harrow_Dialogue = function() { };
harrow_Dialogue.__name__ = true;
harrow_Dialogue.get = function(entry) {
	var map = entry.split(harrow_Library.LINE);
	var choices = [];
	var _g = 0;
	var _g1 = map.length;
	while(_g < _g1) {
		var i = _g++;
		var key = map[i].split(harrow_Library.ITEM);
		var choice = new harrow_Choice();
		choice.text = key[0];
		choice.type = key[1];
		choice.data = key[2];
		choice.mode = key[3];
		choice.role = key[4];
		choices.push(choice);
	}
	return choices;
};
var harrow_Format = function() { };
harrow_Format.__name__ = true;
harrow_Format.variable = function(entry) {
	if(entry.indexOf("[") == -1) {
		return entry;
	}
	var rex = new EReg("\\[(.*?)\\]","gi");
	entry = rex.map(entry,function(r) {
		var matching = r.matched(0);
		var variable = matching.substring(1,matching.length - 1);
		if(harrow_Storage.has(variable)) {
			return harrow_Storage.get(variable);
		}
		return matching;
	});
	return entry;
};
var harrow_Library = function() { };
harrow_Library.__name__ = true;
harrow_Library.get = function(entry) {
	var res = entry.split(harrow_Library.LF);
	var story = new harrow_Story();
	var line = 0;
	while(line < res.length) {
		var node = harrow_Library.getNode(res,line);
		if(node != null && node.type != harrow_Library.EMPTY) {
			var page = new harrow_Page();
			page.type = node.type;
			page.text = node.text;
			page.data = node.data;
			story.data.push(page);
			line += node.depth;
		}
		++line;
	}
	return story;
};
harrow_Library.getNode = function(res,page) {
	var string = StringTools.trim(res[page]);
	if(string.length == 0) {
		return null;
	}
	var node = new harrow_Node();
	var type = "text";
	var leading = string.substring(0,1);
	if(leading == "#") {
		type = "route";
	}
	if(leading == "-") {
		type = "dialogue";
	}
	if(leading == "[") {
		type = harrow_Library.isEvent(string);
	}
	if(leading == "/") {
		type = harrow_Library.EMPTY;
	}
	if(harrow_Library.isBreak(string)) {
		type = "break";
	}
	node.type = type;
	if(type == "text") {
		harrow_Library.getText(node,string);
	}
	if(type == "route") {
		var route = StringTools.replace(string,"#","");
		node.text = StringTools.trim(route);
	}
	if(type == "dialogue") {
		harrow_Library.getDialogue(node,res,page);
	}
	if(type == "event") {
		harrow_Library.getEvent(node,string);
	}
	return node;
};
harrow_Library.getText = function(node,res) {
	var raw = StringTools.replace(res,harrow_Library.COLON,harrow_Library.LINE);
	var key = raw.split(harrow_Library.KEY);
	node.text = StringTools.trim(key.pop());
	node.text = StringTools.replace(node.text,harrow_Library.LINE,harrow_Library.KEY);
	node.data = key.length > 0 ? StringTools.trim(key[harrow_Library.TYPE]) : "";
	if(!harrow_Library.parseSpeaker) {
		node.text = res;
	}
};
harrow_Library.getDialogue = function(node,res,indent) {
	var dialogue = [];
	var _g = indent;
	var _g1 = res.length;
	while(_g < _g1) {
		var page = _g++;
		var sampled = StringTools.trim(res[page]);
		var allowed = sampled.substring(0,2) != harrow_Library.DASH + harrow_Library.DASH;
		var leading = sampled.substring(0,1);
		if(leading == harrow_Library.DASH && allowed) {
			dialogue.push(res[page]);
		} else {
			break;
		}
	}
	var content = "";
	var string = "";
	var _g = 0;
	var _g1 = dialogue.length;
	while(_g < _g1) {
		var i = _g++;
		string = dialogue[i];
		string = StringTools.replace(string,harrow_Library.DASH,"");
		string = harrow_Library.getDialogueItem(string);
		var divider = harrow_Library.LINE;
		if(i == dialogue.length - 1) {
			divider = "";
		}
		content = content + string + divider;
	}
	node.text = content;
	node.data = dialogue.length == 1 ? "button" : "dialogue";
	node.depth = dialogue.length - 1;
};
harrow_Library.getDialogueItem = function(res) {
	var key = res.split(harrow_Library.KEY);
	var text = StringTools.trim(key[harrow_Library.TYPE]);
	var type = "empty";
	var data = "empty";
	var mode = "empty";
	var role = "empty";
	if(key.length > 1) {
		var string = StringTools.trim(key[harrow_Library.TEXT]);
		string = StringTools.replace(string,harrow_Library.SPACE,harrow_Library.KEY);
		var prop = string.split(harrow_Library.KEY);
		if(harrow_Library.isVariable(prop[harrow_Library.TEXT])) {
			type = "variable";
			data = string;
		} else {
			type = "route";
			data = StringTools.trim(key[harrow_Library.TEXT]);
		}
	}
	if(key.length > 2) {
		mode = StringTools.trim(key[harrow_Library.DATA]);
		mode = StringTools.replace(mode,harrow_Library.SPACE,harrow_Library.KEY);
	}
	if(key.length > 3) {
		role = StringTools.trim(key[harrow_Library.PROP]);
		role = StringTools.replace(role,harrow_Library.SPACE,harrow_Library.KEY);
	}
	return text + harrow_Library.ITEM + type + harrow_Library.ITEM + data + harrow_Library.ITEM + mode + harrow_Library.ITEM + role;
};
harrow_Library.getEvent = function(node,res) {
	var string = res.substring(1,res.length - 1);
	string = StringTools.trim(string);
	string = StringTools.replace(string,harrow_Library.COMA + harrow_Library.SPACE,harrow_Library.COMA);
	string = StringTools.replace(string,harrow_Library.SPACE + harrow_Library.SPACE,harrow_Library.KEY);
	string = StringTools.replace(string,harrow_Library.SPACE,harrow_Library.KEY);
	var key = string.split(harrow_Library.KEY);
	var type = key[harrow_Library.TYPE];
	node.type = "event";
	node.text = StringTools.replace(string,type + ":","");
	node.data = type;
	if(type == "move") {
		node.type = "move";
		node.text = StringTools.replace(string,"move:","");
		node.text = StringTools.replace(node.text,harrow_Library.KEY,harrow_Library.SPACE);
	}
	if(type == "story") {
		node.type = "move";
		node.text = StringTools.replace(string,"story:","");
		node.text = StringTools.replace(node.text,harrow_Library.KEY,harrow_Library.SPACE);
	}
	if(type == "lock" || type == "close") {
		node.type = "move";
		node.text = type;
	}
	if(type == "if") {
		node.type = "condition";
		node.text = StringTools.replace(string,"if:","");
	}
	if(type == "else" || type == "end") {
		node.type = "condition";
		node.text = type;
	}
	if(harrow_Library.isVariable(key[harrow_Library.TEXT])) {
		node.type = "variable";
		node.text = string;
	}
};
harrow_Library.isBreak = function(entry) {
	var leading = entry.substring(0,2);
	if(leading == harrow_Library.DASH + harrow_Library.DASH) {
		return true;
	}
	return false;
};
harrow_Library.isEvent = function(entry) {
	if(entry.indexOf("]") != entry.length - 1) {
		return "text";
	}
	return "event";
};
harrow_Library.isVariable = function(entry) {
	if(entry == "=" || entry == "+" || entry == "-" || entry == "*" || entry == "/") {
		return true;
	}
	if(entry == "is" || entry == "roll" || entry == "chance") {
		return true;
	}
	return false;
};
var harrow_Node = function() {
	this.depth = 0;
	this.data = "";
	this.text = "";
	this.type = "";
};
harrow_Node.__name__ = true;
var harrow_Logic = function() { };
harrow_Logic.__name__ = true;
harrow_Logic.variable = function(entry) {
	var key = entry.split(harrow_Library.KEY);
	var name = key.shift();
	var type = key.shift();
	var prop = key.join(harrow_Library.SPACE);
	if(type != null) {
		switch(type) {
		case "*":
			var a = parseFloat(harrow_Logic.get(name));
			var b = parseFloat(harrow_Logic.get(prop));
			harrow_Logic.set(name,Std.string(a * b));
			break;
		case "+":
			var a = parseFloat(harrow_Logic.get(name));
			var b = parseFloat(harrow_Logic.get(prop));
			harrow_Logic.set(name,Std.string(a + b));
			break;
		case "-":
			var a = parseFloat(harrow_Logic.get(name));
			var b = parseFloat(harrow_Logic.get(prop));
			harrow_Logic.set(name,Std.string(a - b));
			break;
		case "/":
			var a = parseFloat(harrow_Logic.get(name));
			var b = parseFloat(harrow_Logic.get(prop));
			harrow_Logic.set(name,Std.string(a / b));
			break;
		case "=":
			harrow_Logic.set(name,harrow_Logic.get(prop));
			break;
		case "chance":
			var prob = harrow_Logic.random.chance(harrow_Logic.get(prop));
			harrow_Logic.set(name,prob == null ? "null" : "" + prob);
			break;
		case "roll":
			var roll = harrow_Logic.random.dice(harrow_Logic.get(prop));
			harrow_Logic.set(name,roll == null ? "null" : "" + roll);
			break;
		default:
		}
	}
};
harrow_Logic.condition = function(entry) {
	if(entry == "else") {
		return false;
	}
	if(entry == "end") {
		return true;
	}
	var key = entry.split(harrow_Library.KEY);
	var name = key.shift();
	var type = key.shift();
	var prop = key.join(harrow_Library.SPACE);
	var result = false;
	if(type != null) {
		switch(type) {
		case "<":
			var a = parseFloat(harrow_Logic.get(name));
			var b = parseFloat(harrow_Logic.get(prop));
			result = a < b;
			break;
		case "<=":
			var a = parseFloat(harrow_Logic.get(name));
			var b = parseFloat(harrow_Logic.get(prop));
			result = a <= b;
			break;
		case "=":
			result = harrow_Logic.get(name) == harrow_Logic.get(prop);
			break;
		case ">":
			var a = parseFloat(harrow_Logic.get(name));
			var b = parseFloat(harrow_Logic.get(prop));
			result = a > b;
			break;
		case ">=":
			var a = parseFloat(harrow_Logic.get(name));
			var b = parseFloat(harrow_Logic.get(prop));
			result = a >= b;
			break;
		case "chance":
			result = harrow_Logic.random.chance(harrow_Logic.get(prop));
			break;
		case "is":
			result = harrow_Logic.get(name) == harrow_Logic.get(prop);
			break;
		default:
		}
	}
	return result;
};
harrow_Logic.get = function(entry) {
	if(entry == "false" || entry == "true") {
		return entry;
	}
	if(harrow_Storage.has(entry)) {
		return harrow_Storage.get(entry);
	}
	return entry;
};
harrow_Logic.set = function(entry,value) {
	harrow_Storage.set(entry,value);
};
var harrow_Page = function() {
	this.data = "";
	this.text = "";
	this.type = "";
};
harrow_Page.__name__ = true;
var harrow_Runtime = function(entry) {
	this.story = entry;
};
harrow_Runtime.__name__ = true;
harrow_Runtime.prototype = {
	nextPage: function() {
		if(this.story.get_end()) {
			this.onEnd();
		}
		if(this.story.get_end()) {
			return;
		}
		this.page = this.story.next();
		this.onPage(this.page);
		switch(this.page.type) {
		case "break":
			this.nextPage();
			break;
		case "condition":
			var condition = harrow_Logic.condition(this.page.text);
			if(condition == false) {
				this.story.skip();
			}
			this.nextPage();
			break;
		case "dialogue":
			var dialogue = harrow_Dialogue.get(this.page.text);
			var _g = 0;
			while(_g < dialogue.length) {
				var choice = dialogue[_g];
				++_g;
				choice.text = harrow_Format.variable(choice.text);
			}
			this.onDialogue(dialogue);
			break;
		case "event":
			this.gameEvent();
			break;
		case "move":
			if(this.page.data == "story") {
				this.onStory(this.page.text);
			}
			if(this.page.data == "close") {
				this.onClose();
			}
			if(this.page.data == "move") {
				this.story.move(this.page.text);
				this.nextPage();
			}
			break;
		case "route":
			break;
		case "text":
			var text = harrow_Format.variable(this.page.text);
			this.onText(text,this.page.data);
			break;
		case "variable":
			harrow_Logic.variable(this.page.text);
			this.nextPage();
			break;
		default:
		}
	}
	,gameEvent: function() {
		switch(this.page.data) {
		case "scene":
			this.onEvent(this.page.data,this.page.text);
			break;
		case "transition":
			this.onTransition();
			break;
		case "wait":
			var time = Std.parseInt(this.page.text);
			haxe_Timer.delay($bind(this,this.nextPage),time * 60);
			break;
		default:
			this.onEvent(this.page.data,this.page.text);
			this.nextPage();
		}
	}
	,onChoice: function(type,data) {
		if(type == "route") {
			this.story.move(data);
		}
		if(type == "variable") {
			harrow_Logic.variable(data);
		}
		this.nextPage();
	}
	,onPage: function(page) {
	}
	,onText: function(text,name) {
	}
	,onDialogue: function(dialogue) {
	}
	,onEvent: function(type,data) {
	}
	,onTransition: function() {
	}
	,onStory: function(name) {
	}
	,onClose: function() {
	}
	,onEnd: function() {
	}
};
var harrow_Storage = function() { };
harrow_Storage.__name__ = true;
harrow_Storage.get = function(key) {
	return harrow_Storage.variable.h[key];
};
harrow_Storage.set = function(key,value) {
	harrow_Storage.variable.h[key] = value;
};
harrow_Storage.has = function(key) {
	return Object.prototype.hasOwnProperty.call(harrow_Storage.variable.h,key);
};
var harrow_Story = function() {
	this.page = -1;
	this.data = [];
};
harrow_Story.__name__ = true;
harrow_Story.prototype = {
	next: function() {
		if(this.page < this.data.length) {
			this.page += 1;
		}
		return this.data[this.page];
	}
	,move: function(route) {
		var _g = 0;
		var _g1 = this.data.length;
		while(_g < _g1) {
			var i = _g++;
			if(this.data[i].type == "route" && this.data[i].text == route) {
				return this.page = i;
			}
		}
		return this.page;
	}
	,skip: function() {
		var position = this.page + 1;
		var _g = position;
		var _g1 = this.data.length;
		while(_g < _g1) {
			var i = _g++;
			if(this.data[i].type == "condition") {
				if(this.data[i].text == "end" || this.data[i].text == "else") {
					return this.page = i;
				}
			}
		}
		return this.page;
	}
	,turn: function(number) {
		if(number < 0 || number > this.data.length - 1) {
			return this.page;
		}
		return this.page = number;
	}
	,look: function(number) {
		if(number < 0 || number > this.data.length - 1) {
			return null;
		}
		return this.data[number];
	}
	,find: function(type,text) {
		var _g = 0;
		var _g1 = this.data.length;
		while(_g < _g1) {
			var i = _g++;
			if(this.data[i].type == type && this.data[i].text == text) {
				return i;
			}
			if(text == "any" && this.data[i].type == type) {
				return i;
			}
			if(type == "any" && this.data[i].text == text) {
				return i;
			}
		}
		return null;
	}
	,get_end: function() {
		return this.page == this.data.length - 1;
	}
};
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	get_native: function() {
		return this.__nativeException;
	}
});
var haxe_Timer = function(time_ms) {
	var me = this;
	this.id = setInterval(function() {
		me.run();
	},time_ms);
};
haxe_Timer.__name__ = true;
haxe_Timer.delay = function(f,time_ms) {
	var t = new haxe_Timer(time_ms);
	t.run = function() {
		t.stop();
		f();
	};
	return t;
};
haxe_Timer.prototype = {
	stop: function() {
		if(this.id == null) {
			return;
		}
		clearInterval(this.id);
		this.id = null;
	}
	,run: function() {
	}
};
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
});
var haxe_ds_StringMap = function() {
	this.h = Object.create(null);
};
haxe_ds_StringMap.__name__ = true;
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var $_;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
String.__name__ = true;
Array.__name__ = true;
js_Boot.__toStr = ({ }).toString;
harrow_Library.LF = "\n";
harrow_Library.EMPTY = "";
harrow_Library.SPACE = " ";
harrow_Library.COLON = "::";
harrow_Library.LINE = "|";
harrow_Library.ITEM = "::";
harrow_Library.COMA = ",";
harrow_Library.DASH = "-";
harrow_Library.KEY = ":";
harrow_Library.parseSpeaker = true;
harrow_Library.TYPE = 0;
harrow_Library.TEXT = 1;
harrow_Library.DATA = 2;
harrow_Library.PROP = 3;
harrow_Logic.random = new harrow_Random();
harrow_Storage.variable = new haxe_ds_StringMap();
App.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
